---
inventory:
  plugin: nornir.plugins.inventory.simple.SimpleInventory
  options:
    host_file: "./hosts_a.yaml"
    group_file: "~/nornir_inventory/groups.yaml"
    defaults_file: "~/nornir_inventory/defaults.yaml"

